include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - avoid_empty_else: true
    - avoid_relative_lib_imports: true
    - avoid_returning_null_for_future: true
    - avoid_slow_async_io: true
    - avoid_types_as_parameter_names: true
    - cancel_subscriptions: true
    - close_sinks: true
    - control_flow_in_finally: true
    - empty_statements: true
    - hash_and_equals: true
    - iterable_contains_unrelated_type: true
    - list_remove_unrelated_type: true
    - no_duplicate_case_values: true
    - no_logic_in_create_state: true
    - prefer_void_to_null: true
    - throw_in_finally: true
    - unnecessary_statements: true
    - unrelated_type_equality_checks: true
    - use_key_in_widget_constructors: true
    - valid_regexps: true
    - always_declare_return_types: true
    - always_require_non_null_named_parameters: true
    - annotate_overrides: true
    - avoid_bool_literals_in_conditional_expressions: true
    - avoid_catching_errors: true
    - avoid_classes_with_only_static_members: false
    - avoid_function_literals_in_foreach_calls: true
    - avoid_init_to_null: true
    - avoid_null_checks_in_equality_operators: true
    - avoid_renaming_method_parameters: true
    - avoid_return_types_on_setters: true
    - avoid_returning_null: true
    - avoid_single_cascade_in_expression_statements: true
    - avoid_unnecessary_containers: true
    - avoid_unused_constructor_parameters: true
    - await_only_futures: true
    - camel_case_types: true
    - constant_identifier_names: true
    - curly_braces_in_flow_control_structures: true
    - directives_ordering: true
    - empty_catches: true
    - empty_constructor_bodies: true
    - implementation_imports: true
    - library_names: true
    - library_prefixes: true
    - non_constant_identifier_names: true
    - overridden_fields: true
    - package_api_docs: false
    - package_names: true
    - package_prefixed_library_names: true
    - prefer_adjacent_string_concatenation: true
    - prefer_collection_literals: true
    - prefer_conditional_assignment: true
    - prefer_const_constructors: true
    - prefer_contains: true
    - prefer_equal_for_default_values: true
    - prefer_final_fields: true
    - prefer_initializing_formals: true
    - prefer_is_empty: true
    - prefer_is_not_empty: true
    - prefer_single_quotes: true
    - prefer_typing_uninitialized_variables: true
    - recursive_getters: true
    - slash_for_doc_comments: true
    - sort_constructors_first: true
    - test_types_in_equals: true
    - type_init_formals: true
    - unawaited_futures: true
    - unnecessary_brace_in_string_interps: true
    - unnecessary_const: true
    - unnecessary_getters_setters: true
    - unnecessary_lambdas: true
    - unnecessary_new: true
    - unnecessary_null_aware_assignments: true
    - unnecessary_null_in_if_null_operators: true
    - unnecessary_overrides: true
    - unnecessary_parenthesis: true
    - unnecessary_this: true
    - use_rethrow_when_possible: true

analyzer:
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
    # allow self-reference to deprecated members (we do this because otherwise we have
    # to annotate every member in every test, assert, etc, when we deprecate something)
    deprecated_member_use_from_same_package: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
  exclude:
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"